"""Pedagogy Planner — application service over Learning/Curriculum/Scheduler/
Conversation/User Configuration views. Owns no canonical truth.

docs/DOMAIN_MODEL.md §10-§12. Decision/execution-status separation types are
canonically defined in elc.platform.types and re-exported here.

P7-0 (TASK-OPI-b99560d4-….36 ③) adds :mod:`elc.planner.feature_assembly` — the
authority boundary BF-02 §5 states (``feature_assembly_status`` /
``snapshot_status`` / ``missing_authorities[]``, and the rule that an
incomplete assembly is DEGRADED carrying no decision).

P7-1 (TASK-OPI-fc9d8ca7-….4) adds :mod:`elc.planner.kernel` — §10.1's eleven
steps as executable code (canonicalize → authoritative feature assembly →
planning-context validity → hard eligibility → policy utility →
coverage-starvation safeguard → per-candidate activation → explicit-request
priority → Pareto prune → near-tie deterministic tie-break → SELECT /
NO_TARGET), over P7-0's record, with a trace that answers "what would have been
selected, and why".

P7-2 (TASK-OPI-fc9d8ca7-….13) adds the **supply side** the kernel consumes:
:mod:`elc.planner.candidates` (§6's Track A / Track B generators, both lanes
ending in the one :class:`~elc.planner.kernel.CandidateProposal`),
:mod:`elc.planner.scope` (§12's ``UserIntentScope`` resolution plus §13's
``ConversationPriorityView``) and :mod:`elc.planner.supply` (the §8.1 content
readiness gate and BF-02 §11's prerequisite resolver). The pipeline from a
:class:`~elc.planner.types.PlanningRequest` and the shadow-mode run are still
later cuts' work items, and :class:`PlannerService` remains the Phase 0
skeleton.
"""

from elc.planner.candidates import (
    ABSENT_READINGS,
    BANDLESS_FACTORS,
    CANDIDATE_SOURCES,
    COMMON_FACES,
    FACTOR_BAND_VALUES,
    OBSERVATION_FIELD,
    REFUSAL_GATES,
    SCAFFOLD_BANDS,
    SOURCE_AUTHORITY,
    SOURCE_READINGS,
    SOURCE_TRACK,
    TRACK_A_SOURCES,
    TRACK_B_SOURCES,
    UNLANDED_AUTHORITIES,
    CandidateAuthority,
    CandidateSupply,
    CandidateSupplyError,
    CandidateSupplyInputs,
    OpportunityObservation,
    ReviewRowPort,
    ReviewViewPort,
    SchedulePort,
    SourceGap,
    SourceReading,
    SupplyTargetPort,
    TargetRefusal,
    TargetRowPort,
    TargetSupplyPort,
    TrackASource,
    TrackBSource,
    generate_candidates,
    generate_track_a,
    generate_track_b,
)
from elc.planner.commands import PlannerCommands
from elc.planner.controller import PlannerService
from elc.planner.feature_assembly import (
    FEATURE_ASSEMBLY_MODEL_VERSION,
    POLICY_PROFILE_MAPPING_VERSION,
    SCHEDULE_URGENCY_BANDS,
    TEACHING_FREQUENCY_TO_PROFILE,
    AuthorityName,
    FeatureAssemblyStatus,
    FeatureAuthority,
    GoalPortfolioPort,
    LearningSnapshotPort,
    PlannerProfile,
    ProfileMapping,
    ScheduleAuthority,
    ScheduleRowPort,
    ScheduleViewPort,
    SnapshotStatus,
    TeachingPolicyPort,
    assemble_feature_authority,
    execution_status_of,
    goal_relevance_of,
    profile_mapping_of,
    schedule_authority_of,
    schedule_urgency_of,
)
from elc.planner.kernel import (
    AUTHORITY_ASSEMBLED_FACTORS,
    BENEFIT_FACTORS,
    BENEFIT_WEIGHTS,
    COST_FACTORS,
    COST_WEIGHTS,
    KERNEL_STEP_ORDER,
    PLANNER_KERNEL_MODEL_VERSION,
    PLANNER_PROFILE_VERSION,
    POLICY_PROFILES,
    TIE_BREAK_ORDER,
    TIE_EPSILON,
    ActivationPath,
    BenefitFactor,
    CandidateProposal,
    CandidateTrace,
    CanonicalCandidate,
    ContextTrace,
    CostFactor,
    CoverageServiceState,
    DegradedReason,
    ExclusionReason,
    FactorAssembly,
    FactorGap,
    FactorReading,
    FactorSource,
    GoalRelation,
    KernelResult,
    KernelStep,
    NoTargetReason,
    PlannerInputError,
    PlannerTrace,
    PlanningInput,
    PolicyProfileParameters,
    PrerequisiteState,
    ReadinessLevel,
    TieBreakCriterion,
    assemble_candidate_factors,
    canonicalize_proposals,
    plan,
    runtime_decision_outcome_of,
)
from elc.planner.queries import PlannerQueries
from elc.planner.scope import (
    FLOW_PRIORITY_WORDS,
    FLOW_TO_INTERRUPTION_COST_BAND,
    INTERACTION_PHASE_WORDS,
    REACHABLE_SCOPE_WORDS,
    UNPRODUCED_SCOPE_WORDS,
    ConversationPriorityView,
    FlowPriority,
    InteractionPhase,
    RequestedTarget,
    ScopeResolution,
    interruption_cost_band_of,
    resolve_user_intent_scope,
)
from elc.planner.supply import (
    APPROVED_LINK_EDITORIAL_STATUS,
    CONFIRMED_GAP_FLAG,
    INSUFFICIENT_EVIDENCE_FLAG,
    REALIZES_RELATION,
    LearnerStatePort,
    PrerequisiteOutcome,
    PrerequisitePort,
    ReadinessOutcome,
    ReadinessPort,
    prerequisite_state_of,
    readiness_of_target,
)
from elc.planner.types import (
    InitiativeClass,
    LearningIntent,
    PlannerDecision,
    PlannerDecisionOutcome,
    PlannerEvaluation,
    PlannerExecutionStatusRecord,
    PlannerExecutionStatusValue,
    PlanningOutcome,
    PlanningRequest,
    TargetCandidate,
    TargetMode,
    UserIntentScope,
)

__all__ = [
    "ABSENT_READINGS",
    "APPROVED_LINK_EDITORIAL_STATUS",
    "AUTHORITY_ASSEMBLED_FACTORS",
    "BANDLESS_FACTORS",
    "BENEFIT_FACTORS",
    "BENEFIT_WEIGHTS",
    "CANDIDATE_SOURCES",
    "COMMON_FACES",
    "CONFIRMED_GAP_FLAG",
    "COST_FACTORS",
    "COST_WEIGHTS",
    "FACTOR_BAND_VALUES",
    "FEATURE_ASSEMBLY_MODEL_VERSION",
    "FLOW_PRIORITY_WORDS",
    "FLOW_TO_INTERRUPTION_COST_BAND",
    "INSUFFICIENT_EVIDENCE_FLAG",
    "INTERACTION_PHASE_WORDS",
    "KERNEL_STEP_ORDER",
    "OBSERVATION_FIELD",
    "REACHABLE_SCOPE_WORDS",
    "REALIZES_RELATION",
    "REFUSAL_GATES",
    "SCAFFOLD_BANDS",
    "SOURCE_AUTHORITY",
    "SOURCE_READINGS",
    "SOURCE_TRACK",
    "TRACK_A_SOURCES",
    "TRACK_B_SOURCES",
    "PLANNER_KERNEL_MODEL_VERSION",
    "PLANNER_PROFILE_VERSION",
    "POLICY_PROFILES",
    "POLICY_PROFILE_MAPPING_VERSION",
    "SCHEDULE_URGENCY_BANDS",
    "TEACHING_FREQUENCY_TO_PROFILE",
    "TIE_BREAK_ORDER",
    "TIE_EPSILON",
    "ActivationPath",
    "AuthorityName",
    "BenefitFactor",
    "CandidateAuthority",
    "CandidateProposal",
    "CandidateSupply",
    "CandidateSupplyError",
    "CandidateSupplyInputs",
    "CandidateTrace",
    "CanonicalCandidate",
    "ContextTrace",
    "ConversationPriorityView",
    "CostFactor",
    "CoverageServiceState",
    "DegradedReason",
    "ExclusionReason",
    "FlowPriority",
    "InteractionPhase",
    "LearnerStatePort",
    "OpportunityObservation",
    "PrerequisiteOutcome",
    "PrerequisitePort",
    "ReadinessOutcome",
    "ReadinessPort",
    "RequestedTarget",
    "ReviewRowPort",
    "ReviewViewPort",
    "SchedulePort",
    "ScopeResolution",
    "SourceGap",
    "SourceReading",
    "SupplyTargetPort",
    "TargetRefusal",
    "TargetRowPort",
    "TargetSupplyPort",
    "TrackASource",
    "TrackBSource",
    "UNLANDED_AUTHORITIES",
    "UNPRODUCED_SCOPE_WORDS",
    "FactorAssembly",
    "FactorGap",
    "FactorReading",
    "FactorSource",
    "FeatureAssemblyStatus",
    "FeatureAuthority",
    "GoalPortfolioPort",
    "GoalRelation",
    "InitiativeClass",
    "KernelResult",
    "KernelStep",
    "LearningIntent",
    "LearningSnapshotPort",
    "NoTargetReason",
    "PlannerCommands",
    "PlannerDecision",
    "PlannerDecisionOutcome",
    "PlannerEvaluation",
    "PlannerExecutionStatusRecord",
    "PlannerExecutionStatusValue",
    "PlannerInputError",
    "PlannerProfile",
    "PlannerQueries",
    "PlannerService",
    "PlannerTrace",
    "PlanningInput",
    "PlanningOutcome",
    "PlanningRequest",
    "PolicyProfileParameters",
    "PrerequisiteState",
    "ProfileMapping",
    "ReadinessLevel",
    "ScheduleAuthority",
    "ScheduleRowPort",
    "ScheduleViewPort",
    "SnapshotStatus",
    "TargetCandidate",
    "TargetMode",
    "TeachingPolicyPort",
    "TieBreakCriterion",
    "UserIntentScope",
    "assemble_candidate_factors",
    "assemble_feature_authority",
    "canonicalize_proposals",
    "execution_status_of",
    "generate_candidates",
    "generate_track_a",
    "generate_track_b",
    "goal_relevance_of",
    "interruption_cost_band_of",
    "plan",
    "prerequisite_state_of",
    "profile_mapping_of",
    "readiness_of_target",
    "resolve_user_intent_scope",
    "runtime_decision_outcome_of",
    "schedule_authority_of",
    "schedule_urgency_of",
]
