"""Teaching domain — TeachingMoment lifecycle + the Teaching Gate.

docs/DOMAIN_MODEL.md §14/§15. Gate is the only "may execute now" authority.

Phase 3 P3-1A wiring: the Gate's USER_INITIATED OPEN profile lives in
elc.teaching.gate (frozen BF-03 v1.1 semantics, no behavioral_baselines
import), the durable CP2 / Gate store in elc.teaching.store, the target
resolution port in elc.teaching.targets, the command shape + canonical
payload in elc.teaching.request, and the authority face in
elc.teaching.controller.

Phase 3 P3-1B adds the active-teaching turn faces: the response envelope
(elc.teaching.envelope), the pure evaluator (elc.teaching.evaluator), the
presentation ladder (elc.teaching.ladder), the §8 limits
(elc.teaching.limits), the DECIDING_NEXT_ACTION branch table
(elc.teaching.next_action), the evidence-proposal boundary
(elc.teaching.evidence) and the pure turn-step assembly
(elc.teaching.flow). Review F10 syncs this package face with those modules:
a public module no __all__ names is a face a consumer cannot find, and a
package whose __all__ lags its own surface silently hides the slice.
"""

from elc.teaching.commands import TeachingCommands
from elc.teaching.controller import TeachingController
from elc.teaching.envelope import (
    ATTEMPTLESS_CONTROL_INTENTS,
    CONTROL_INTENTS,
    ENVELOPE_STEPS,
    TEACHING_RESPONSE_TYPE,
    AttemptPayload,
    EnvelopeStep,
    TeachingControlIntent,
    TeachingResponseEnvelope,
    envelope_refusal,
    parse_teaching_response_payload,
    teaching_response_payload,
)
from elc.teaching.evaluator import (
    ATTEMPT_EVALUATOR_ID,
    ATTEMPT_EVALUATOR_VERSION,
    EVALUATION_BASES,
    TARGET_UNRESOLVED_BASIS,
    AttemptAnswerKey,
    AttemptEvaluation,
    evaluate_attempt,
    normalize_answer,
    unjudgeable_evaluation,
)
from elc.teaching.evidence import (
    CAPABILITY_LINKAGE_CLAIM_ROLE,
    FOCUS_CLAIM_ROLE,
    TeachingEvidenceProposal,
    build_evidence_proposal,
    performance_type_for,
)
from elc.teaching.flow import (
    ATTEMPT_OPPORTUNITY_TYPE,
    DEGRADED_ABORT_REASON,
    answer_key_for,
    attempt_record_for,
    closing_reason_for_gate_denial,
    continuation_facts_for,
    continuation_index_for,
    evaluation_record_for,
    evidence_proposal_refs_for,
    opportunity_id_for,
)
from elc.teaching.gate import (
    CONTINUATION_ACTIONS,
    CONTINUATION_REASON_CODES,
    DENY_PRECEDENCE,
    GATE_POLICY_VERSION,
    MISSING_OR_UNKNOWN_FACT_KEYS,
    USER_INITIATED_CONTINUATION_INTENTS,
    USER_INITIATED_OPEN_INTENTS,
    USER_INITIATED_OPEN_REASON_CODES,
    ContinuationFacts,
    GateInputError,
    GateVerdict,
    UserInitiatedOpenFacts,
    decide_user_initiated_open,
    decide_user_requested_continuation,
    with_lock_state,
)
from elc.teaching.ladder import (
    HINT_PHASES,
    LADDER_PHASES,
    POST_REVEAL_PHASES,
    LadderStep,
    evidence_support_level,
    is_post_reveal_attempt,
    ladder_step,
    ladder_step_refusal,
    phase_rank,
    support_rank,
)
from elc.teaching.limits import (
    CLOSING_DELIVERY_KINDS,
    HARD_ATTEMPT_LIMIT,
    HARD_TEACHING_TURN_LIMIT,
    LIMITS_V0,
    LIMITS_V0_VERSION,
    RETRY_LIKE_DELIVERY_KINDS,
    SOFT_ATTEMPT_LIMIT,
    SOFT_TEACHING_TURN_LIMIT,
    TEACHING_TURN_ACTION_TYPES,
    LimitVerdict,
    TeachingLimits,
    TeachingLoad,
    continuation_verdict,
)
from elc.teaching.next_action import (
    NextAction,
    closing_outcome_for,
    decide_next_action,
)
from elc.teaching.queries import TeachingQueries
from elc.teaching.request import (
    TeachingRequest,
    intent_scope_for_request,
    parse_teaching_request_payload,
    teaching_request_payload,
)
from elc.teaching.store import (
    CP2OpenRequest,
    MomentTransition,
    SqliteTeachingStore,
    StaleStoreEpochError,
    cp2_action_intent,
)
from elc.teaching.targets import (
    TeachingTargetProvider,
    TeachingTargetView,
)
from elc.teaching.types import (
    ABORT_REASONS,
    ATTEMPT_OUTCOMES,
    COMPLETION_OUTCOMES,
    AbortReason,
    AnswerExposureState,
    AttemptEvaluationRecord,
    AttemptOutcome,
    AttemptRecord,
    AuthorizationBasis,
    CompletionOutcome,
    EphemeralTeachingDirective,
    ExposureEstimateCertainty,
    GateDecisionContext,
    GateDecisionRecord,
    GateDecisionValue,
    GateExecutionStatusRecord,
    GateExecutionStatusValue,
    MomentSource,
    MomentState,
    PresentationPhase,
    ResumeDirective,
    TeachingMomentRecord,
    TeachingSupportLevel,
    TeachingTargetRef,
)

__all__ = [
    "ABORT_REASONS",
    "ATTEMPTLESS_CONTROL_INTENTS",
    "ATTEMPT_EVALUATOR_ID",
    "ATTEMPT_EVALUATOR_VERSION",
    "ATTEMPT_OPPORTUNITY_TYPE",
    "ATTEMPT_OUTCOMES",
    "AbortReason",
    "AnswerExposureState",
    "AttemptAnswerKey",
    "AttemptEvaluation",
    "AttemptEvaluationRecord",
    "AttemptOutcome",
    "AttemptPayload",
    "AttemptRecord",
    "AuthorizationBasis",
    "CAPABILITY_LINKAGE_CLAIM_ROLE",
    "CLOSING_DELIVERY_KINDS",
    "COMPLETION_OUTCOMES",
    "CONTINUATION_ACTIONS",
    "CONTINUATION_REASON_CODES",
    "CONTROL_INTENTS",
    "CP2OpenRequest",
    "CompletionOutcome",
    "ContinuationFacts",
    "DEGRADED_ABORT_REASON",
    "DENY_PRECEDENCE",
    "ENVELOPE_STEPS",
    "EVALUATION_BASES",
    "EphemeralTeachingDirective",
    "EnvelopeStep",
    "ExposureEstimateCertainty",
    "FOCUS_CLAIM_ROLE",
    "GATE_POLICY_VERSION",
    "GateDecisionContext",
    "GateDecisionRecord",
    "GateDecisionValue",
    "GateExecutionStatusRecord",
    "GateExecutionStatusValue",
    "GateInputError",
    "GateVerdict",
    "HARD_ATTEMPT_LIMIT",
    "HARD_TEACHING_TURN_LIMIT",
    "HINT_PHASES",
    "LADDER_PHASES",
    "LIMITS_V0",
    "LIMITS_V0_VERSION",
    "LadderStep",
    "LimitVerdict",
    "MISSING_OR_UNKNOWN_FACT_KEYS",
    "MomentSource",
    "MomentState",
    "MomentTransition",
    "NextAction",
    "POST_REVEAL_PHASES",
    "PresentationPhase",
    "RETRY_LIKE_DELIVERY_KINDS",
    "ResumeDirective",
    "SOFT_ATTEMPT_LIMIT",
    "SOFT_TEACHING_TURN_LIMIT",
    "SqliteTeachingStore",
    "StaleStoreEpochError",
    "TARGET_UNRESOLVED_BASIS",
    "TEACHING_RESPONSE_TYPE",
    "TEACHING_TURN_ACTION_TYPES",
    "TeachingCommands",
    "TeachingControlIntent",
    "TeachingController",
    "TeachingEvidenceProposal",
    "TeachingLimits",
    "TeachingLoad",
    "TeachingMomentRecord",
    "TeachingQueries",
    "TeachingRequest",
    "TeachingResponseEnvelope",
    "TeachingSupportLevel",
    "TeachingTargetProvider",
    "TeachingTargetRef",
    "TeachingTargetView",
    "USER_INITIATED_CONTINUATION_INTENTS",
    "USER_INITIATED_OPEN_INTENTS",
    "USER_INITIATED_OPEN_REASON_CODES",
    "UserInitiatedOpenFacts",
    "answer_key_for",
    "attempt_record_for",
    "build_evidence_proposal",
    "closing_outcome_for",
    "closing_reason_for_gate_denial",
    "continuation_facts_for",
    "continuation_index_for",
    "continuation_verdict",
    "cp2_action_intent",
    "decide_next_action",
    "decide_user_initiated_open",
    "decide_user_requested_continuation",
    "envelope_refusal",
    "evaluate_attempt",
    "evaluation_record_for",
    "evidence_proposal_refs_for",
    "evidence_support_level",
    "intent_scope_for_request",
    "is_post_reveal_attempt",
    "ladder_step",
    "ladder_step_refusal",
    "normalize_answer",
    "opportunity_id_for",
    "parse_teaching_request_payload",
    "parse_teaching_response_payload",
    "performance_type_for",
    "phase_rank",
    "support_rank",
    "teaching_request_payload",
    "teaching_response_payload",
    "unjudgeable_evaluation",
    "with_lock_state",
]
